spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: tis_prod
    url: jdbc:postgresql://localhost:5432/tis_prod
    username: postgres
    password: 121201gui
  database:
    driverClassName: org.postgresql.Driver
server:
  port: 7000