spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: tis_prod
    url: jdbc:postgresql://localhost:5432/tis_prod
    username: postgres
    password: 121201gui
  database:
    driverClassName: org.postgresql.Driver
server:
  port: 7000
---
spring:
  config.activate.on-profile: development
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/tis_prod
    username: tis_prod
    password: 12345
  database:
    driverClassName: org.postgresql.Driver
server:
  port: 7000
---
spring:
  config.activate.on-profile: deploy
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://silly.db.elephantsql.com:5432/moljttsr
    username: moljttsr
    password: YA3fCSC63zCRq5YcqcyM8MGB_aGG_8Xc
  database:
    driverClassName: org.postgresql.Driver
server:
  port: 8080

